### ISSUE TITLE
Issue with « submol

### ISSUE THREAD

**Issue by paveleremin** [hidehalo/emoji#8]
After decode it's transforms to Â
@hidehalo could you check please?

**Comment by hidehalo** [comment]
@paveleremin Sorry for reply late, could you provide entire string for the case?

I run codes:
```php
<?php
require __DIR__.'/vendor/autoload.php';

use Hidehalo\Emoji\Core;

$str = "«";
$core = new Core;
$encoded = $core->encode($str);
$decoded = $core->decode($encoded);

echo $encoded.PHP_EOL;
echo $decoded.PHP_EOL;
```
And I get those:
```php
«
«
```
It's seem nothing happened, I need more detail for this fault. thx

**Comment by hidehalo** [comment]
Emma... run the same code as mine? can you check out the repository's version?
Or
```$composer update hidehalo/emoji```

**Comment by paveleremin** [comment]
> composer update hidehalo/emoji
Nothing to install or update

**Comment by hidehalo** [comment]
@paveleremin Congratulations, you found a BUG

**Comment by paveleremin** [comment]
@hidehalo could you please make a patch release? i.e. 0.1.4

**Comment by hidehalo** [comment]
@paveleremin Ofcauz thx for your feed back, great job! :)
