### ISSUE TITLE
Some emojis are not filtered

### ISSUE THREAD

**Issue by kappit** [hidehalo/emoji#9]
I tested out the clean method in the Core class using the following files:

http://unicode.org/Public/emoji/11.0/

Some of the emojis do not get filtered.

**Comment by hidehalo** [comment]
Sorry for my late reply. I am very happy you would test it, the main reason is this repo base on emoji 5.0 data.btw, I have realized this repo is hard to be comfortable with emoji data updates #7 but change that is not easy. thx for your testing, I am already working on new solution (a big one) ; )

**Comment by kappit** [comment]
You are welcome!

I wish PHP had better ways to  filter emojis.

I wish you good luck with your new solution, and I look forward to it :)

**Comment by hidehalo** [comment]
@kappit You can check branch [v1.0](https://github.com/hidehalo/emoji/tree/v1.0) for now, it is almost done

**Comment by kappit** [comment]
Looks promising. :-)

**Comment by hidehalo** [comment]
@kappit Thx! xD 
I am already finished unit tests,but I still hope you can make sure it is solve your issue.
download and use it plz, if you have any confuse about using that just ask me, I am a living manual Lol

**Comment by hidehalo** [comment]
@kappit I already release version 1.0, you can use ```$composer update``` get latest version and check it.

**Comment by kappit** [comment]
So I have finally tested the new version, and it seems to be working really great! Awesome :) 👍

**Comment by hidehalo** [comment]
@kappit Thank you!
